spring.application.name=openrouter
server.port=8090

# OpenRouter
openrouter.base-url=https://openrouter.ai/api/v1
openrouter.api-key=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
openrouter.default-model=openai/gpt-4o
openrouter.max-tokens=512
openrouter.timeout-seconds=30


# Security
app.security.api-key=Susheel23!
jwt.secret=thisIsASecretKeyForJwtAuthenticationThisIsASecretKeyForJwtAuthentication
jwt.expiration=3600000
